### ISSUE TITLE
Third-party mirroring support

### ISSUE THREAD

**Issue by XuehaiPan** [Homebrew/glibc-bootstrap#6]
The `glibc` formula is now a default dependency for all formulae on Linux if the system `glibc < 2.35`. The users need to download the bootstrap files if they cannot use the pre-built bottle of `glibc` (e.g., unsupported prefix/cellar).

The resource URLs in the `resource` block are hardcoded in the `glibc.rb`:

https://github.com/Homebrew/homebrew-core/blob/379fea565f21d730cf01987f5571fa0dc4823792/Formula/glibc.rb#L64-L99

Can we support third-party mirroring by `HOMEBREW_BOTTLE_DOMAIN` like `portable-ruby`? I'm not sure this the right place to create this issue. Maybe it should be handled by `Homebrew/brew`.

**Comment by MikeMcQuaid** [comment]
> Can we support third-party mirroring by `HOMEBREW_BOTTLE_DOMAIN` like `portable-ruby`? I'm not sure this the right place to create this issue. Maybe it should be handled by `Homebrew/brew`.

This seems like a good idea. It'll need implemented in Homebrew/brew. We will review a PR provided it is not too invasive.
